title: Engineering Application
description: A GitHub Pages to interactively manage my list of repository.
baseurl: ""
url: "https://jmsweb.github.io"
show_downloads: true
google_analytics:
github: [metadata]

pages_list:
  About: '/about'
  Archive: '/blog'
  Feed: '/feed.xml'

# Build settings
theme: null
plugins:
 - jekyll-feed
 - jekyll-seo-tag