# Site settings
title: jmsweb
email: no-rely@jmsweb.github.com
description: > # this means to ignore newlines until "baseurl:"
  A simple personal blog and portfolio site.
baseurl:  # the subpath of your site, e.g. /blog/
url: https://jmsweb.github.io/  # the base hostname & protocol for your site
github_url: https://www.github.com/jmsweb
linkedin_url: https://www.linkedin.com/in/jmsweb/
twitter_username: twitter_username
github_username:  jmsweb

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

