title: Engineering Application
description: A GitHub Pages to interactively manage my list of repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jmsweb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: true
google_analytics:
github: [metadata]
theme: null # To force no css in build
plugins:
  - jekyll-seo-tag
  - jekyll-feed

pages_list:
  About: '/about'
  Archive: '/blog'
  Feed: '/feed.xml'
